#──────────────────────────────────────────────────────────────────────
# Development Environment START
#──────────────────────────────────────────────────────────────────────
spring:
  #──────────────────────────────────────────────────────────────────────
  # Setting DataSource for development
  # IP로 접근할 경우 정상적으로 DB 접근이 되지 않은(오류가 많이 발생 이유 확인 필요)
  #──────────────────────────────────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://34.64.85.181:5432/apti-dev?currentSchema=parking
    username: apti
    password: aptidev12#$
    drive-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10           # Max Connection size 10개
      connection-timeout: 5000        # Connection Timeout 시간 5초
      connection-init-sql: SELECT 1   # Connection 초기 SQL
      validation-timeout: 2000        # 유효성 Timeout 시간 2초
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  #──────────────────────────────────────────────────────────────────────
  # Setting the JPA Environment for development
  #──────────────────────────────────────────────────────────────────────
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  #──────────────────────────────────────────────────────────────────────
  # Setting the Springboot Admin for development
  #──────────────────────────────────────────────────────────────────────
  boot:
    admin:
      url: http://172.19.1.68:8080 # server  url
      client:
        url: http://172.19.1.68:8080
        username: apti
        password: '@monitor'
        instance:
          metadata:
            user.name: apti
            user.password: '@monitor'
          service-url: http://34.64.240.208:8085 # client url
          name: 'DEV-주차예약 API Server'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

#──────────────────────────────────────────────────────────────────────
# Setting the Server Port for development
#──────────────────────────────────────────────────────────────────────
server:
  port: 8085
#──────────────────────────────────────────────────────────────────────
# Setting Logging Level for development
#──────────────────────────────────────────────────────────────────────
logging:
  #──────────────────────────────────────────────────────────────────────
  # Setting classpath of Logback for development
  #──────────────────────────────────────────────────────────────────────
  level:
    org:
      #──────────────────────────────────────────────────────────────────────
      # Setting logging level of hibernate  for development
      #──────────────────────────────────────────────────────────────────────
      hibernate:
        type: trace
        SQL: info
#──────────────────────────────────────────────────────────────────────
# Setting the Local APT-I API URL(Need to be set the Domain instead of IP
#──────────────────────────────────────────────────────────────────────
apti:
  apiUri: http://34.64.221.108:8080/api/v2/common/user/information
#──────────────────────────────────────────────────────────────────────
# Development Environment END
#──────────────────────────────────────────────────────────────────────
